#!/bin/sh

export THEOS="${THEOS:-$HOME/theos-roothide}"
export THEOS_PACKAGE_SCHEME=roothide
export THEOS_DEVICE_IP="${THEOS_DEVICE_IP:-127.0.0.1}"
export THEOS_DEVICE_PORT="${THEOS_DEVICE_PORT:-58422}"
export THEOS_DEVICE_SIMULATOR=
